### ISSUE TITLE
Possible to modify starting HP values?

### ISSUE THREAD

**Issue by Netmonmatt** [thomasneff/mmbn3-draft-gauntlet#1]
Hey, just stumbled on this project and honestly it looks pretty dang awesome. The only thing that frustrates me is that I really can't seem to get past the first few fights due to how easy it is to get a very disadvantageous starting custom screen with problematic enemy setups. I get that it's a randomizer, but when your starting HP is 150 it's very easy to get a bad setup that will kill you before you can deal with it. Is there a way to change starting HP values, or maybe allow the player to pick more than one starting buff?

**Comment by thomasneff** [comment]
Hi!

Awesome that you like it. I agree, with the base difficulty settings it can be brutally difficult at times.

There are (now) several options to "tune" the difficulty:

1. Choose a different loadout: some loadouts (like the MMBN3 base folder) are inherently more difficult than others, such as the Draft Folder (Random) that lets you draft from all chips in the game. I mostly tested the game using the "Draft Folder (Balanced / Rarity-Based)", with which I have been able to get quite consistent runs. Purely random folders are more chaotic and unbalanced, while the MMBN3 base folder is brutally difficult. 
2. I just added another menu at the start that lets you pick from some pre-configured difficulties, that allow for more MaxHP or more buffs. Maybe this will already be enough for you to have fun :-)
3. If you're at least somewhat proficient in editing code/text files, you can also edit the raw source code. The source for the new difficulty files is in difficulty_levels/mmbn3_blue_us/ , where you can adjust max HP values, buff frequency, and theoretically everything else as well. There is no documentation though, so you're on your own with that.

Hope that answers your question!

**Comment by Netmonmatt** [comment]
Ah, I didn't notice those in the main release, I guess those were added after the current release build.
I'll make sure to check out the more recent releases then. Thanks for replying, I appreciate it!

**Comment by thomasneff** [comment]
Those features were just added before I posted my comment, inspired by your comment :-)

**Comment by Netmonmatt** [comment]
Oh, sweet! I'm looking forward to trying it out then.
