### ISSUE TITLE
Issue running gauntlet.lua - can't write outside memory size

### ISSUE THREAD

**Issue by darren-stoll** [thomasneff/mmbn3-draft-gauntlet#2]
![image](https://user-images.githubusercontent.com/9387346/112777407-6a6ea280-8fff-11eb-9482-d1330735553e.png)

I'm not entirely sure how to get around this, but I did follow the directions to the best of my understanding. I'm not trying to run it with the music mod, for reference.

When it is running while this happens, it can only advance a frame every 10 seconds, and it'll eventually crash.

**Comment by thomasneff** [comment]
Hi!

You should be able to fix this by setting `GENERIC_DEFS.ENABLE_MUSIC_PATCHING = 0` in line 13 of `music_loader.lua` with a standard text editor.

At least I just tried and it works with an unmodified ROM and music patching disabled that way. It should also be possible to detect if the ROM is big enough to allow for music patching, so I can add an automatic check to prevent this error.

Let me know if you still have issues when changing the above line to disable music patching!

**Comment by darren-stoll** [comment]
That fixed the problem. Thanks so much!
